US33: SSO POST - Filter special characters for password
at-internship/at-sso-api pull request #15
Opened 2020-11-26 18:43 UTC by KevinRSantillan

Filter space and "line break" characters from password field.

2020-11-28 00:22 UTC, ivanflores15 requested changes

2020-11-28 00:22 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/services/BusinessValidations.java
> +public static void filterCharacters(String password) {
your method should be private.

2020-11-28 00:25 UTC, ivanflores15 requested changes

2020-11-28 00:25 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/services/BusinessValidations.java
>  					PathErrorMessage.pathApi, HttpStatus.BAD_REQUEST);
pathApi should follow standar for constans in java as PATH_API

2020-11-28 01:41 UTC, ivanflores15 approved these changes

2020-11-30 20:37 UTC, Bwore approved these changes

2020-12-01 00:54 UTC, merged