Feature/us 50 put operation to update users
at-internship/at-sso-api pull request #21
Opened 2021-04-26 16:01 UTC by Gra2411

2021-04-26 17:17 UTC, ivanflores15 requested changes
Generally, don't change previuos behavior for error Handling or log4j

2021-04-26 17:17 UTC, ivanflores15 commented on pom.xml
> +<!--			<exclusions>-->
If you will not use this exclusion is better remove it

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/controller/ControllerApplication.java
> +	@PostMapping(value = "/api/v1/user", produces = "application/json")
As far I remember we include @RequestMapping tag to define base path, is that rigth?

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/controller/GlobalExceptionHandler.java
> -package com.agilethought.internship.sso.controller;
Don't remove this class, it belongs to previuos behaviors, you need to adapt your code to this handler

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/exception/BadRequestException.java
> -import lombok.Getter;
Don't change previous behaviors for handler exception

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethought/internship/sso/exception/HttpMessageNotReadableException.java
> -/*package com.agilethought.internship.sso.exception;
Don't remove

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethougth/intership/sso/errorhandling/HttpExceptionMessage.java
> -package com.agilethougth.intership.sso.errorhandling;
don't remove

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/java/com/agilethougth/intership/sso/errorhandling/PathErrorMessage.java
> -package com.agilethougth.intership.sso.errorhandling;
Don't remove

2021-04-26 17:17 UTC, ivanflores15 commented on src/main/resources/log4j2.properties
> +status=error
Don't change previous behavior

2021-04-26 19:23 UTC, ivanflores15 commented
please rebase to current develop reference

2021-04-27 21:58 UTC, luisgalindoluna reviewed
I noticed your approach for this was to delete some classes and modify the behavior in the Implementation so it wouldn't use them anymore and then paste our classes in the ServiceImpl.
I don't doubt that it works, but is that how we wanted to do it? I was under the impression we'd migrate our own classes rather than modify the existing ones.

2021-04-29 15:34 UTC, closed without merging