Feature/at sso 21
at-internship/at-sso-api pull request #6
Opened 2020-10-13 13:31 UTC by Bwore

Swagger implementation to show available methods. 
Add dependency and the class SwaggerConfig to the project.

2020-10-13 17:11 UTC, rodrigo-velasco approved these changes

2020-10-13 21:58 UTC, at-internship requested changes

2020-10-13 21:58 UTC, at-internship commented on src/main/java/com/agilethought/internship/sso/swagger/SwaggerConfig.java
> +				.apis(RequestHandlerSelectors.basePackage("com.agilethought.internship.sso.controller"))
Indent Code

2020-10-13 21:58 UTC, at-internship commented on pom.xml
> +    		<groupId>io.springfox</groupId>
Indent Code

2020-10-14 04:01 UTC, carla-paz approved these changes
A little tip to indent correctly Luis, ctrl+shift+f  In the pom file it is not necessary to select the code, just hit ctrl+shift+f but for the rest of the code do select portions of the code, do not try to do it all at once. Hope this helps!

2020-10-14 14:41 UTC, carla-paz approved these changes
Looks good!

2020-10-14 14:50 UTC, at-internship approved these changes

2020-10-14 14:51 UTC, merged